# Zephyr log subsys
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3

# Activate shell
CONFIG_SHELL=y
CONFIG_SHELL_BACKEND_SERIAL=y

# Activate serial console
CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_STDOUT_CONSOLE=y
CONFIG_UART_LINE_CTRL=y

# Led strip
CONFIG_LED_STRIP=y